# Copyright 2024 The Outline Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'

vars:
  # This needs to be updated if the file moves.
  REPO_ROOT: '{{joinPath .TASKFILE_DIR "../.."}}'
  OUT_DIR: '{{joinPath .REPO_ROOT "output/client"}}'
  BIN_DIR: '{{joinPath .OUT_DIR "/bin"}}'

tasks:
  cli:
    desc: "Build the Outline CLI"
    internal: true
    requires: {vars: [TARGET_OS, TARGET_ARCH, ZIG_TARGET]}
    vars:
      CLI_VERSION: "v1.0.0-cli"
      OUTPUT: '{{.OUT_DIR}}/{{.TARGET_OS}}-{{.TARGET_ARCH}}/outline-cli{{if eq .TARGET_OS "windows"}}.exe{{end}}'
    cmds:
      - rm -rf "{{dir .OUTPUT}}" && mkdir -p "{{dir .OUTPUT}}"
      - |
        GOOS={{.TARGET_OS}} GOARCH={{.TARGET_ARCH}} CGO_ENABLED=1 \
        CC='zig cc -target {{.ZIG_TARGET}}' \
        go build -trimpath -ldflags="-s -w -X=main.version={{.CLI_VERSION}}" -o '{{.OUTPUT}}' '{{.TASKFILE_DIR}}/outline/cmd/outline-cli'

  windows:
    deps: [windows:386]

  windows:*: 
    desc: "Build the Outline CLI for Windows"
    vars:
      TARGET_ARCH: '{{index .MATCH 0 | default "386"}}'
      CC_ARCH: '{{get (dict "amd64" "x86_64" "arm64" "aarch64" "386" "x86" ) .TARGET_ARCH | default .TARGET_ARCH}}'
    cmds:
      - {task: cli, vars: {TARGET_OS: "windows", TARGET_ARCH: "{{.TARGET_ARCH}}", ZIG_TARGET: "{{.CC_ARCH}}-windows-gnu"}}

  linux:
     deps: [linux:amd64]

  linux:*: 
    desc: "Build the Outline CLI for Linux"
    vars:
      TARGET_ARCH: '{{index .MATCH 0 | default "amd64"}}'
      CC_ARCH: '{{get (dict "amd64" "x86_64" "arm64" "aarch64" "386" "x86" ) .TARGET_ARCH | default .TARGET_ARCH}}'
    cmds:
      - {task: cli, vars: {TARGET_OS: "linux", TARGET_ARCH: "{{.TARGET_ARCH}}", ZIG_TARGET: "{{.CC_ARCH}}-linux-gnu.2.27"}}

  clean:
    cmds:
      - rm -rf '{{.OUT_DIR}}'
      - go clean -i -r '{{.TASKFILE_DIR}}/outline'
